"""Neo4j Cypher export — writes a .cypher file importable via neo4j-admin or LOAD CSV.

No live Neo4j connection needed; produces a standalone Cypher script.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional, Union

from .base_exporter import BaseExporter


class Neo4jExporter(BaseExporter):
    def export(
        self,
        unified_graph: "UnifiedCallGraph",  # noqa: F821
        output_path: Union[str, Path],
        *,
        knowledge_graph: Optional["KnowledgeGraph"] = None,  # noqa: F821
        communities: Optional[list] = None,
        god_nodes: Optional[list] = None,
    ) -> Path:
        out = Path(output_path)
        god_set = {g.full_name for g in (god_nodes or [])}

        node_community: dict = {}
        for community in (communities or []):
            for m in community.members:
                node_community[m] = community.id

        lines = [
            "// Generated by callflow-tracer — import with: neo4j-admin database import",
            "// Or paste into Neo4j Browser",
            "",
        ]

        # MERGE nodes
        for node in unified_graph.nodes.values():
            name_esc = node.full_name.replace("'", "\\'")
            is_god = str(node.full_name in god_set).lower()
            community_id = node_community.get(node.full_name, -1)
            is_llm = str(node.full_name.startswith("llm.")).lower()
            lines.append(
                f"MERGE (n:Function {{name: '{name_esc}'}}) "
                f"SET n.call_count={node.call_count}, "
                f"n.total_time={round(node.total_time, 6)}, "
                f"n.is_god_node={is_god}, "
                f"n.community={community_id}, "
                f"n.is_llm={is_llm};"
            )

        lines.append("")

        # MERGE edges
        for edge in unified_graph.edges():
            caller_esc = edge.caller.replace("'", "\\'")
            callee_esc = edge.callee.replace("'", "\\'")
            lines.append(
                f"MATCH (a:Function {{name: '{caller_esc}'}}), "
                f"(b:Function {{name: '{callee_esc}'}}) "
                f"MERGE (a)-[r:CALLS]->(b) "
                f"SET r.call_count={edge.call_count}, "
                f"r.total_time={round(edge.total_time, 6)};"
            )

        # Knowledge graph edges if provided
        if knowledge_graph is not None:
            lines.append("")
            lines.append("// Knowledge graph semantic edges")
            for kg_edge in knowledge_graph._edges:
                if kg_edge.rel_type.value == "CALLS":
                    continue  # already covered above
                src_esc = kg_edge.source.replace("'", "\\'")
                tgt_esc = kg_edge.target.replace("'", "\\'")
                rel = kg_edge.rel_type.value
                lines.append(
                    f"MATCH (a {{name: '{src_esc}'}}), (b {{name: '{tgt_esc}'}}) "
                    f"MERGE (a)-[:{rel} {{weight: {round(kg_edge.weight, 4)}}}]->(b);"
                )

        out.write_text("\n".join(lines), encoding="utf-8")
        return out
